// data.js

const data = {
  teil1: [
    { word: "Stadt Friedichsberg", number: 235 },
    { word: "Unwetterschäden", number: 14 },
    { word: "Bierkonsum", number: 345 },
    { word: "Lufthansa", number: 23 },
    { word: "in den Alpen", number: 23 },
    { word: "Insel Bali", number: 45 },
    { word: "Bio Spiegel", number: 15 },
    { word: "Erdbeben", number: 15 },
    { word: "Fluggesellschaft", number: 15 },
    { word: "Schladminger Ski", number: 15 },
    { word: "Das Schladminger", number: 125 },
    { word: "Deutsches Schiff", number: 125 },
    { word: "Bundesländer", number: 125 },
    { word: "Nicht sicher", number: 14 },
    { word: "Die Wahlbeteiligung", number: 13 },
    { word: "Der Bau", number: 134 },
    { word: "Es ist unklar", number: 14 },
    { word: "BILD AM SONNTAG", number: 123 },
    { word: "vier Tage pro", number: 12 },
    { word: "Meeresküsten", number: 25 },
    { word: "Die Quote der Hochschulabsolventen", number: 24 },
    { word: "Die Zahl der Arbeitslosen", number: 124 },
    { word: "Die Konjunkturentwicklung negativ", number: 12 },
    { word: "internationale Konferenz", number: 13 },
    { word: "Deutsche Filmmuseum", number: 24 },
    { word: "Um Tickets zu gewinnen", number: 24 },
    { word: "Laut Statistischem Bundesamt", number: 145 },
    { word: "Bei der Sportveranstaltung", number: 24 },
    { word: "Nach Ansicht mancher", number: 24 },

    // ✅ Added from image but missing in your code
    { word: "Die 50 Euro", number: 13 },
    { word: "Berlin", number: 15 },
    { word: "Für ein Projekt mit Manager", number: 13 },
    { word: "Das Bundesfamilienministerium", number: 24 },
    { word: "Bauern waren", number: 24 },
    { word: "Bei den Europawahlen die CDU", number: 135 },
    { word: "Ein Treffen bei der Integrationsbeauftragten", number: 16 },
    { word: "Für die Polizei in Berlin", number: 1245 },
  ],

  teil2: [
    { word: "Meron Makeba", number: 4590 },
    { word: "Roland spielen", number: 234790 },
    { word: "Roland aufsteigen", number: 3479 },
    { word: "Roland höhere Liga", number: 23589 },
    { word: "Frau Kidder", number: 124589 },
    { word: "Julia", number: 13458 },
    { word: "Tu dresden", number: 35780 },
    { word: "Professor Steiner", number: 290 },
    { word: "Mallorca", number: 347 },
    { word: "Die Zahl der Deutschen", number: 347 },
    { word: "Carina", number: 134890 },
    { word: "Beim Wettkampf", number: 1246 },
    { word: "Nadin", number: 235680 },
    { word: "Markus", number: 24580 },
    { word: "In dem Restaurant", number: 13489 },
    { word: "Suza Hotop", number: 1348 },
    { word: "Frau Schenk", number: 14678 },
    { word: "Herr Karimov", number: 25890 },
    { word: "Herr Gasser und Frau Janke", number: 34890 },
    { word: "Die Deutsche machen", number: 3459 },
    { word: "Franz Schumachker", number: 124680 },
    { word: "Herr Scherer", number: 340 },
    { word: "Zu Beginn", number: 1234689 },
    { word: "Vanessa", number: 234680 },
  ],
  teil3: [
    { word: "Telefon KG", number: 1 },
    { word: "Raum C23", number: 2 },
    { word: "Internet prüfen", number: 15 },
    { word: "Ehrenamts", number: 15 },
    { word: "Das Geschäft", number: 15 },
    { word: "Anrufbeantworter", number: 15 },
    { word: "Radio Konzert", number: 13 },
    { word: "Für ein Konzert", number: 24 },
    { word: "Reitturnier", number: 13 },
    { word: "Musikfestivals", number: 13 },
    { word: "Fahrschule", number: 14 },
    { word: "Süden Deutschlands regen", number: 14 },
    { word: "Süden Deutschlands Schnee", number: 15 },
    { word: "im August", number: 34 },
    { word: "Neue AutoBahn", number: 34 },
    { word: "Delikatessen", number: 234 },
    { word: "Demonstration", number: 25 },
    { word: "Blutspenden", number: 1345 },
    { word: "Buchhandlungen", number: 135 },
    { word: "Trainin Auffahrten", number: 24 },
    { word: "Fandbüro", number: 125 },
    { word: "Ausgang 26", number: 145 },
    { word: "Am Wochenanfang", number: 123 },
    { word: "Funktion", number: 125 },
    { word: "Angebot", number: 125 },
    { word: "Rettumtest", number: 13 },
    { word: "Wanderung", number: 2 },
    { word: "Die Gruppe Die Prinzen", number: 14 },
    { word: "spätestens in Hannover", number: 123 },
    { word: "Für das Konzert mit Romano", number: 35 },
    { word: "Bayern Radio", number: 145 },
    { word: "Gartenausstellung 50Ga", number: 214 },
    { word: "den Opel-Zoo", number: 13 },
    { word: "Der Christbüchermarkt in Nürnberg", number: 135 },
    { word: "Das Geschäft für österreichische", number: 15 },
    { word: "Alle Frage der Pugliese", number: 2 },
    { word: "Aufgegebenen", number: 25 },
    { word: "Die Fahrzehörer von Berlin", number: 15 },
    { word: "Die Literaturmesse für Körnerfolger", number: 5 },
    { word: "Einmaligkeit im Output", number: 12 },
    { word: "Das treffen", number: 125 },
    { word: "INTERANZÖTER ZOO", number: 15 },
    { word: "Für ein konzert morgen", number: 34 },
    { word: "Buchbeziehung", number: 15 },
    { word: "Ein Teil der kostenlosen", number: 23 },
    { word: "Auf der Wistosbrücke", number: 34 },
    { word: "Die Buchpräsentation", number: 145 },
    { word: "Beim Gaside-Rado", number: 13 },
    { word: "Ausgänge + (المعدل)", number: 125 },
    { word: "Am Wochenende", number: 345 },
    { word: "Blutspendeinstituts", number: 145 },
    { word: "In Raum C23", number: 13 },
    { word: "Wanderung", number: 22 },
    { word: "Spätestens in Hannover", number: 14 },
    { word: "Für das Konzert", number: 13 },
    { word: "Romano", number: 35 },
    { word: "Das Christkindlmarkt am Marienplatz", number: 145 },
    { word: "Das Geschäft für alles", number: 24 },
    { word: "Alle Flüge der Fluglinie", number: 2 },
    { word: "Die Fahrverbot von „Berlin“", number: 145 },
    { word: "Die Literaturmesse", number: 145 },
    { word: "Fußballspiel im Ostpark", number: 145 },
    { word: "Im FRANKFURT ZOO", number: 25 },
    { word: "Für ein Konzert morgen + (المعدل)", number: 14 },
    { word: "Auf der Viktoriabrücke", number: 13 },
    { word: "Beim Klassik-Radio", number: 13 },
  ],
};
